# TEST RUN
branches:
  only:
  - master
  - stable
language: java
jdk:
- openjdk14
dist: focal
before_install: 
install:
- mvn install -Dgpg.skip=true -P !build-extras -B -V
before_script: 
script: mvn test -P !build-extras -B
cache:
  directories:
  - "~/.m2/repository"
after_success:
- "./cd/deploy.sh"
after_failure: 
